services:
  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rls-server:
    build:
      context: ../rls-server
      dockerfile: ../rls-server/docker/Dockerfile
    depends_on:
      - redis
    env_file:
      - ../.env
    ports:
      - "50051:50051"

  api-server:
    build:
      context: ../api-server
      dockerfile: ../api-server/docker/Dockerfile
    depends_on:
      - rls-server
    env_file:
      - ../.env
    ports:
      - "8080:8080"

volumes:
  redis_data:
